### ISSUE TITLE
Addition of IUPAC Name in output

### ISSUE THREAD

**Issue by stuchalk** [dan2097/opsin#122]
OPSIN works great for both IUPAC names and CAS names, however if II put a CAS name in I would love to get the IUPAC name out with the other identifiers.  Would that be possible? This is of course an enhancement not a bug...

**Comment by dan2097** [comment]
Unfortunately the algorithm required for name to structure and structure to name are actually quite different, so this is not in scope.

Structure to name in general involves perception of substructures in the complete structure. One also would then have to take into account the rather complex set of priorirty rules IUPAC describes to determine the preferred way of naming thecompound e.g. prefer the highest priority functional group, longest chain etc.

The only "solution" I can think of currently is to retrieve the IUPAC name from a resource like PubChem although obviously that won't cover all compounds.

**Comment by stuchalk** [comment]
Daniel

Ok, I understand.  Thanks.

Stuart

On Jul 12, 2020, at 5:12 PM, Daniel Lowe <notifications@github.com<mailto:notifications@github.com>> wrote:



Unfortunately the algorithm required for name to structure and structure to name are actually quite different, so this is not in scope.

Structure to name in general involves perception of substructures in the complete structure. One also would then have to take into account the rather complex set of priorirty rules IUPAC describes to determine the preferred way of naming thecompound e.g. prefer the highest priority functional group, longest chain etc.

The only "solution" I can think of currently is to retrieve the IUPAC name from a resource like PubChem although obviously that won't cover all compounds.
