### ISSUE TITLE
Cannot find in scope fragment with atom with locant N

### ISSUE THREAD

**Issue by Yadav-Abhi** [dan2097/opsin#123]

**Comment by dan2097** [comment]
What was the name?

**Comment by Yadav-Abhi** [comment]
Cyclopropyl-4-bromo-3-[2-bromoethyl]-9-[N,N-diethylcarbanoyl]-7-[3-formylcyclobutoxy]-6-[4-hydroxycyclohex-2-enyl]-2-nitroso-8,9-dioxonon-6-enoate

**Comment by dan2097** [comment]
It's probably a typo of:

Cyclopropyl-4-bromo-3-[2-bromoethyl]-9-[N,N-diethylcarbamoyl]-7-[3-formylcyclobutoxy]-6-[4-hydroxycyclohex-2-enyl]-2-nitroso-8,9-dioxonon-6-enoate

(carbanoyl-->carbamoyl)
