### ISSUE TITLE
More amino acids: Nortryptophan, Nortyrosine and Norcitrulline

### ISSUE THREAD

**Issue by rogersayle** [dan2097/opsin#124]
Hi Daniel,
Please could you add support for the non-standard amino acids Nortryptophan, Nortyrosine and Norcitrulline?
(OPSIN already support Homotryptophan, Homotyrosine and Homocitrulline).  Additionally, it would be nice
if Norphenylalanine was accepted as a synonym for Phenylglycine (but I can't imagined it used much in practice).
Many thanks in advance,
Roger
--

**Comment by dan2097** [comment]
They're rather uncommon trivial names e.g. "nortryptophan" is far more commonly called 3-indolylglycine.
Similarly "Nortyrosine" is more commonly called 4-hydroxyphenylglycine
Norcitrulline while rare at least seems equally uncommon as any other name for that compound
OPSIN supports the homo variants as they are in common use.
I guesss the names are unambiguous though (even without a locant for the nor operator), so it doesn't particularly do any harm to include them.

**Comment by dan2097** [comment]
BTW why does https://pubchem.ncbi.nlm.nih.gov/compound/4-Hydroxyphenylglycine claim nortyrosine to be an IUPAC name? I'm not aware of any use of nor in IUPAC names where it is not preceded by a locant.
The latest IUPAC recomendations I have access to state:
"The position of the skeletal atom that is removed is denoted in all cases by its locants in the numbering of the fundamental parent structure."
