### ISSUE TITLE
1-silacyclopropenylidene or silirene-2-ylidene

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#127]
Hi,

For these two names I get the same structure in OPSIN. However, I am wondering, which one is correct as per IUPAC rules. Please clarify.
[sic2h2-naming-opsin.pdf](https://github.com/dan2097/opsin/files/5170815/sic2h2-naming-opsin.pdf)

Thanks in advance

**Comment by dan2097** [comment]
IUPAC rules describe multiple ways of naming compounds, 1-silacyclopropenylidene uses replacement nomenclature, while silirene-2-ylidene uses Hantzsch-Widman nomenclature.

More recently the IUPAC has produced guidelines for choosing a preferred IUPAC name (https://en.wikipedia.org/wiki/Preferred_IUPAC_name) although this isn't to say that other names are "incorrect".

I think silirene-2-ylidene is preferable, but I'm not certain. I think the 'e' would normally be elided to give: siliren-2-ylidene
