### ISSUE TITLE
Unable to generate name using lambda convension

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#130]
I am having trouble in generating names when the metal atom is in unphysical valency state. For these two compounds (please see the attachment), if you could generate names, it would be great. For compound 1, i have given two resonance forms. Based on transannular C-C bond lengths, I could say that the one on the right hand side is more dominant. Therefore, name for this would be great. For the second one, I have given only one resonance form. Thanks in advance.

**Comment by vthimmakondu** [comment]
structures are attached herewith
[iso1and2.pdf](https://github.com/dan2097/opsin/files/5252453/iso1and2.pdf)

**Comment by dan2097** [comment]
OPSIN only has relatively basic support for IUPAC inorganic nomenclature so is unlikely to be that useful for determining whether inorganic names are correct.

If I understand correctly, the bonds between the carbon and magnesium are covalent rather than coordinate bonds in your sketch. I'm not sure how you would ideally name this in IUPAC nomenclature. For coordinate bonds you would use the η-notation (eta notation), which isn't yet supported by OPSIN.

**Comment by vthimmakondu** [comment]
I would say that OPSIN is quite good even for inorganic names. For example, if you type the following names (related to MgC6H2 isomers, which we had recently worked on and published a paper; DOI: 10.1021/acs.jpca.0c06401) 1-magnesacyclohepta-4-en-2,6-diyne, 3-magnesahepta-1,4,6-triyne, 1-magnesacyclohepta-2,3,4-
trien-6-yne, and 1-magnesahepta-2,4,6-triyne, it indeed gives the correct structures. 

Coming back to the point on MgC3H2 isomers, I initially thought of the following names and gave those names in OPSIN to verify:
(i) 2-magnesiobicyclo[1.1.0]but-1(3)-en-4-yl  (however, this goes to MgC4H2 instead of MgC3H2, which I don't understand)
(ii) For compound 2, I thought of another resonance structure by just making two bonds to Mg instead of three and tried this name: 2-dihydridocarbon-1-magnesacycloprop-2-en-3-yl
However, I got a error message saying, "2-dihydridocarbon-1-magnesacycloprop-2-en-3-yl could be parsed but OPSIN was unsure of the meaning of the words. This error will occur, by default, if a name is just a substituent"

Therefore, I thought that I would reach out to you guys for help. By the way, these are not coordinate bonds. These are covalent bonds for sure.

**Comment by dan2097** [comment]
By analogy to your name the compounds could be named:
2λ<sup>3</sup>-magnesabicyclo[1.1.0]but-1(3)-en-4-yl
1λ<sup>3</sup>-magnesabicyclo[1.1.0]but-3-en-4-yl 

I think these unambiguous describe the given compounds. This naming system comes from IUPAC's organic naming conventions (IUPAC blue book), my uncertainty is whether there is a way of naming this using inorganic naming conventions (IUPAC red book) and if so which is preferred.

**Comment by vthimmakondu** [comment]
Thank you very much. On page 229 of the red book (IR-10 Organometallic compounds) there was one example given using magnesium, which is, [2-(4-methylpent-3-en-1-yl)but-2-ene-1,4-diyl]magnesium. If I cut and paste that name in OPSIN, 
I get the following error:
Error:

Substitutive bond formation failure: Fragment expected to have one OutAtom but had: 2

If I try the other name
[2-(4-methylpent-3-en-1-yl)but-2-ene-1,4-diido-k2C1,C4]magnesium
then I got the following error:
[2-(4-methylpent-3-en-1-yl)but-2-ene-1,4-diido-k2C1,C4]magnesium was uninterpretable due to the following section of the name: o-k2C1,C4] The following was not understandable in the context it was used: k2C1,C4

The inorganic naming convention seem to be somewhat cumbersome. Anyways, thanks again for your help.
