### ISSUE TITLE
alpha locant on thymine

### ISSUE THREAD

**Issue by rogersayle** [dan2097/opsin#131]
Consider the wikipedia page (not created/editted by me)
https://en.wikipedia.org/wiki/5,6-Dihydro-5(%CE%B1-thyminyl)thymine
Implicitly alpha-thyminyl means the methyl at the 5-position, and could probably be supported much like 1-thyminyl, 3-thyminyl, etc.
Thanks in advance.

**Comment by dan2097** [comment]
Thanks I already have this locant on thymidine and  ribosylthymine, so it's inclusion on thymine makes sense. Incidentally the SMILES/InChI on the Wikipedia article appear to be wrong.
