### ISSUE TITLE
IUPAC name for compounds containing planar tetracoordinate carbon atom

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#135]
Hi, 
Let's say I have an isomer of Si2C3H2 elemental composition containing a planar tetracoordinate carbon atom. Please see the figure for the structure. My question is, whether the name given is correct or not. OPSIN generates such a structure but the question is whether the central carbon is in tetrahedral tetracoordination or in planar tetracoordination? I believe "spiro" indicates the former. If so, then how to generate name for compounds containing ptC atom?
![image](https://user-images.githubusercontent.com/70721856/96818694-ce4cc980-13d6-11eb-85f1-cc71276c158f.png)
![IMG_6153](https://user-images.githubusercontent.com/70721856/96818758-ede3f200-13d6-11eb-81da-18ca5824c601.JPG)

**Comment by dan2097** [comment]
As far as I'm aware spiro only implies that rings share a single atom and does not specify the geometry.
https://www.qmul.ac.uk/sbcs/iupac/spiro/sp16p.html#p16 has examples of molecules that are definitely not tetrahedral. Hence I think this name is okay

**Comment by vthimmakondu** [comment]
Hi,

Thank you for the link. While the name I had mentioned earlier for Si2C3H2 is okay, here comes a special situation.
Let us take two different isomers of C5H4. One containing a planar tetracoordinate carbon (ptC) atom and another containing a tetrahedral tetracoordination of central carbon atom. Please see the figure attached. From a quantum chemical perspective, these two are two different isomers (stationary points) of C5H4 with distinct total energies computed at the fc-CCSD(T)/cc-pVTZ level of theory. While the isomer with tetrahedral tetracoordination could be named as spiro[2.2]pent-1-yne, what we should do with the other isomer containing a ptC atom? or vice versa. I understand that "spiro" doesn't necessarily imply the geometry. However, in the vast majority of the cases, the spiro compounds possess tetrahedral tetracoordination of carbon atom instead of ptC atom. 
![c5h4-ptCvsttC](https://user-images.githubusercontent.com/70721856/97095154-d1cb9500-1610-11eb-83bb-a59fc759b0b6.jpg)

**Comment by dan2097** [comment]
You do deal with interesting chemistry :smile:

Unfortunately the latest IUPAC recommendations are only available in print, but i think this sections from the draft recommendations covers this scenario:
https://old.iupac.org/reports/provisional/abstract04/BB-prs310305/Chapter9.pdf [P-92.1.9] 
e.g. they give an example of
(SPY-5-21′)-2,3,5,7,8-pentaphenyl-1,4,6,9-tetraoxa-5λ5-phosphaspiro[4.4]nona-2,7-diene

I don't have access to the 2013 recommendations, although I do have access to an updated draft from 2012. This was essentially the same as the 2004 version, although they had explicitly added SP-4 to the list of commonly encountered geometries (SP=square planar)

My understanding from reading the recommendations was that your latter molecule should be named:
(_SP_-4)-spiro[2.2]pent-1-yne

OPSIN doesn't yet support these nontetrahedral configuration descriptors

**Comment by vthimmakondu** [comment]
Thanks a lot. As you can understand, writing a scientific document without IUPAC name is quite cumbersome. That's why I have to constantly check-in with OPSIN and see whether everything I am doing is okay. This helps a lot.
