### ISSUE TITLE
Correct structure for ionic liquid cation?

### ISSUE THREAD

**Issue by simonmb** [dan2097/opsin#150]
Maybe I am doing something wrong myself, but if I use the following name:
`1-decyl-3-methyl-1H-imidazolium`
I get the following structure:
![1-decyl-3-methyl-1H-imidazolium](https://user-images.githubusercontent.com/6115499/116969945-6e08df80-acb7-11eb-90ad-c9706ef2fbc4.png)

If I use the following name:
`1-Decyl-3-methyl-1H-imidazol-3-ium`
I get the following structure:
![1-Decyl-3-methyl-1H-imidazol-3-ium](https://user-images.githubusercontent.com/6115499/116970017-82e57300-acb7-11eb-94bb-dae98ab7a72e.png)

Am I doing something wrong? Or is opsin doing something wrong?

**Comment by dan2097** [comment]
I think in principle OPSIN should give the same interpretation for both names. In practice OPSIN currently applies the ium suffix before the indicated hydrogen is considered, and hence interprets it incorrectly as `1-decyl-3-methyl-1H-imidazol-1-ium`, moving the application of unlocanted suffixes later is an improvement I'd like to do to OPSIN at some point.
Nonetheless the correct IUPAC name for this compound is `1-Decyl-3-methyl-1H-imidazol-3-ium`, this avoids any potential ambiguity.

**Comment by simonmb** [comment]
> I think in principle OPSIN should give the same interpretation for both names. In practice OPSIN currently applies the ium suffix before the indicated hydrogen is considered, and hence interprets it incorrectly as `1-decyl-3-methyl-1H-imidazol-1-ium`, moving the application of unlocanted suffixes later is an improvement I'd like to do to OPSIN at some point. Nonetheless the correct IUPAC name for this compound is `1-Decyl-3-methyl-1H-imidazol-3-ium`, this avoids any potential ambiguity.

Hi @dan2097 , we are currently working on ILThermo, so a huge database on ionic liquids and it would really help if you implemented the changes you proposed in the comment above.

**Comment by dan2097** [comment]
Fixing it in the way I described is unfortunately quite involved. According to ChEBI (https://www.ebi.ac.uk/chebi/searchId.do?chebiId=50059) imidazolium typically refers to 1H-imidazol-3-ium 
hence in the above commit I've made the far simple change of just having imidazol-3-ium be the default when no locant is given. 

Can you let me know whether this is sufficient to fix the issue you were seeing on other examples . Your original example is now correctly interpreted.

**Comment by simonmb** [comment]
Thank you for implementing this, but I have been using the web interface, so unfortunately I am unable to test the changes.

**Comment by dan2097** [comment]
I've updated the web interface

**Comment by simonmb** [comment]
I can confirm it is working now,
