### ISSUE TITLE
Handle more variants of lipid nomenclature, e.g. sn-glycero-3-phosphate

### ISSUE THREAD

**Issue by rogersayle** [dan2097/opsin#152]
I've two minor requests to handle some of the (poor) naming conventions used by the lipid community (LipidMaps).
The first is that although OPSIN handles sn-glycero-3-phosphocholine and sn-glycero-3-phosphoethanolamine, it
doesn't (yet) handle sn-glycero-3-phosphate (the name used for LIPIDMAPS' PA class, e.g. https://www.lipidmaps.org/databases/lmsd/LMGP10010001?LMID=LMGP10010001).  Pedantically, this name should more correctly be sn-glycerol-3-phosphate (which OPSIN does handle), but there's a lot of the incorrect usage in circulation.
The other minor request is for "rac-glycero-3-phosph..." to be handled in addition to the specified stereochemistry form, e.g.
https://www.goldbio.com/product/38/12-dipalmitoyl-rac-glycero-3-phosphocholine, and likewise without either a "sn-" or "rac-" prefix (which presumably is optional) as in 1-(9Z,12Z,15Z-octadecatrienoyl)-glycero-3-phosphate from HMDB: https://hmdb.ca/metabolites/HMDB0062320.
Many thanks in advance,
Roger

**Comment by rogersayle** [comment]
Another minor lipid-related enhancement request (not worth opening a new issue for)... opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/simpleSubstituents.xml contains support for "sn-glycero-3-phospho", it would be convenient to also support "sn-glycero-1-phospho" (and perhaps even "sn-glycero-2-phospho") as well.

**Comment by dan2097** [comment]
Would you expect the zwitterionic interpretation of phosphocholine as appears on that goldbio link? (if the name doesn't have an explicit counteranion)
`1-(9Z,12Z,15Z-octadecatrienoyl)-glycero-3-phosphate` fails for an additional reason unrelated to this issue. OPSIN doesn't yet use the 9Z,12Z,15Z to position the double bonds.
