### ISSUE TITLE
Migrate from Apache log4j 1.2 to 2.14

### ISSUE THREAD

**Issue by manuelschwarze** [dan2097/opsin#155]
We are using the OPSIN library for many years successfully in cheminformatics environments (mainly around [RDKit and KNIME](https://github.com/rdkit/knime-rdkit)). Big thank you to all contributors who delivered such a stable solution! 

When running OPSIN integrated in our Java platform together with a lot of other Java libraries, we are seeing in the logs that log4j has issues to be configured properly - the log entries refer to log4j coming from OPSIN:

`log4j:WARN No appenders could be found for logger (uk.ac.cam.ch.wwmm.opsin.NameToStructure).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.`

Reason is that the platform-wide configuration of log4j is done with a log4j.xml file (no .properties file) and it assumes that all libraries are working with log4j 2.x. 

I noticed now, that OPSIN is still using the very old log4j 1.2 version. Log4j 2.0 as successor was released in July 2014 (7 years ago) and has grown since that time to version 2.14 today. It would be great, if in the near future the log4j integration of OPSIN could be updated as described here: http://logging.apache.org/log4j/2.x/manual/migration.html - Apparently, this is not something done in 30 mins, but for somebody who knows how OPSIN makes use of log4j it is probably feasible in a short timeframe.

Thanks for considering in advance!

**Comment by dan2097** [comment]
I think this makes sense given Log4j 1.x is no longer being maintained. OPSIN's use of logging is fairly minimal, although I think the way the command-line interface programmatically changes the log level to implement verbose mode is a bit non-standard. I'll try and update Log4J later this week.

**Comment by dan2097** [comment]
OPSIN has two modules, a core module that can convert chemical names to SMILES/CML, and another module that allows direct conversion to InChI/InChIKey. The latter module still has a dependency on Log4j v1 via its dependency on JNI-InChI. I'm not sure if the existing Knime node uses this module. In the nearish future I'm aiming to replace JNI-InChI with a [project ](https://github.com/dan2097/jna-inchi)I'm working on to wrap the current version of InChI.
