### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by thegodone** [dan2097/opsin#161]
opsin provides for METHYLSELENOPYRUVATE 'CCC(C(=[Se])[O-])=O'  while PubChem is 'C[Se]CC(=O)C(=O)O'

https://pubchem.ncbi.nlm.nih.gov/compound/Methylselenopyruvate#section=Canonical-SMILES

**Comment by dan2097** [comment]
This will now produce C[Se]CC(C(=O)[O-])=O  
"ate" terms in general are supposed to be the anionic form, although biochemical nomenclature does tend to play fast and loose with this distinction.
