### ISSUE TITLE
Small molecule polymer not processing

### ISSUE THREAD

**Issue by stuchalk** [dan2097/opsin#168]
I tried poly(ethane-1,2-diol) and it gives an error.  Not sure why as ethane-1,2-diol is the correct IUPAC name for ethylene glycol.

**Comment by dan2097** [comment]
There are two types of naming nomenclature that can be used to describe polymers, source-based or structure-based. Source-based names describe the starting material from which the polymer is derived, while structure-based names indicate the repeat unit.
Something like poly(ethane-1,2-diol) or poly(ethylene glycol) is a source-based name. A structure-based name would be poly(oxyethylene) 

OPSIN only supports structure-based names, as in general the structure of the repeat unit cannot be algorithmically derived from the source monomer(s). To decode a source based name you essentially are trying to predict the most likely way in which these compound(s) might polymerize. The following paper is from a group that's implemented this process:
https://pubs.acs.org/doi/10.1021/acsapm.0c00273
I do not currently consider source-based polymer names to be within OPSIN's scope, although I'm well aware that in the literature they're often vastly more prevalent than structure-based names.

**Comment by stuchalk** [comment]
Thanks for the explanation Daniel.
