### ISSUE TITLE
Unexpected H-count from lamda nomenclature

### ISSUE THREAD

**Issue by IngvarLa** [dan2097/opsin#187]
From patent US20160176875A1
(E)-3-(4-bromophenyl)-1-(7-(2,2,2-trifluoroacetyl)-2,7λ<sup>4</sup>1-diazaspiro[3.5]nonan-2-yl)prop-2-en-1-one
When I tried without the <sup></sup> Opsin reported the λ N as [NH38], that is a nitrogen with 38 hydrogens, gave me chuckle.  As it is from a patent, there may be something wrong with the name, missing space or hyphen.  Any suggestion.

**Comment by dan2097** [comment]
As far as I can see from looking at the patent, the 1 after the superscript 4 is erroneous. The structure (https://patentimages.storage.googleapis.com/fb/24/4d/9ae345c4ff4aca/US20160176875A1-20160623-C00024.png) appears to correspond to:

(E)-3-(4-bromophenyl)-1-(7-(2,2,2-trifluoroacetyl)-2,7λ4-diazaspiro[3.5]nonan-2-yl)prop-2-en-1-one

I'm not sure where the 1 came from.

**Comment by IngvarLa** [comment]
Thanks Daniel.  Closing this, as the problem is with the name, not Opsin.
