### ISSUE TITLE
Phthalhydrazide

### ISSUE THREAD

**Issue by IngvarLa** [dan2097/opsin#201]
Opsin gives phthalhydrazide as C(C=1C(C(=O)NN)=CC=CC1)(=O)NN
Many/most other sources say: O=C1NNC(C2=C1C=CC=C2)=O
including ChemDraw, ChemSpider, ChemicalBook, PubChem, Sigma-Aldrich and other suppliers.
Even, if as I assume Opsin is correct, this looks like a loosing battle.
Had it only been the structure itself I could add a dictionary term to override, but as it is used as a base.
E.g., 3-aminophthalhydrazide for luminol it would be good to include this in Opsin

**Comment by dan2097** [comment]
I think I should add it as a trivial name. Just to note this means that phthal**o**hydrazide will retain the original structure.

**Comment by IngvarLa** [comment]
Sounds good.  Matches ChemDraw behaviour for phthalohydrazide.
