### ISSUE TITLE
Failed on trying the example file

### ISSUE THREAD

**Issue by wenchangzhou-qtx** [dan2097/opsin#208]
Hi there,

I was trying the example molecule acetamide, this might be a silly issue on my side, but would like to get help, thanks!

The command I run is 
`java -jar opsin-cli-2.7.0-jar-with-dependencies.jar -osmi input.txt output.txt
`
```
more input.txt
NameToStructure nts = NameToStructure.getInstance();
String smiles = nts.parseToSmiles("acetamide");
```

Then I got error:
```
NameToStructure nts = NameToStructure.getInstance(); is unparsable due to the following being uninterpretable: NameToStructure nts = NameToStructure.getInstance(); The following was not parseable: NameToStructure nts = NameToStructure.getInstance();
String smiles = nts.parseToSmiles(''acetamide''); is unparsable due to the following being uninterpretable: String smiles = nts.parseToSmiles(''acetamide''); The following was not parseable: String smiles = nts.parseToSmiles(''acetamide'');
```

**Comment by wenchangzhou-qtx** [comment]
I have installed Java 8 on my Mac

**Comment by dan2097** [comment]
```
NameToStructure nts = NameToStructure.getInstance();
String smiles = nts.parseToSmiles("acetamide");
```
Is the code you would use if you're calling OPSIN from your own Java program.

For command-line usage the file you're reading from just needs to contain chemical names. So input.txt should just contain:
acetamide

**Comment by wenchangzhou-qtx** [comment]
Thanks! @dan2097 Now it is working. I have to say OPSIN is amazing!
