### ISSUE TITLE
Prefix form of lutidine, i.e. 2,3-lutidin-4-yl

### ISSUE THREAD

**Issue by rogersayle** [dan2097/opsin#209]
An odd quirk of OPSIN is that it doesn't accept prefix forms from some traditional (hetereocyclic) parents.  Hence, 4-chloro-2,3-lutidine is valid, but 2,3-lutidin-4-yl isn't. Admittedly, this usage is uncommon (e.g. https://pubs.acs.org/doi/abs/10.1021/acs.macromol.7b01007) but it seems an unintended exception to the rule (heuristic?) that parents/heterocycles can be turned into prefixes by dropping the terminal "e" and replacing it with yl.  For example, "caffein-8-yl" is considered valid for OPSIN.

**Comment by dan2097** [comment]
IUPAC names only have a finite list of pre-functionalized groups that can be used as parents. I typically add trivial names initially as not allowing suffixes, then allow them if empirically the name is used with them.
In the case of lutidine it would need to be considered whether only radical adding suffixes like yl should be allowed or all suffixes e.g. is lutidinol more likely to be lutidine subtituted with OH or an unrelated trivial name. I'll check this specific case when I'm back from vacation

**Comment by dan2097** [comment]
There's a lutidinic acid which leads to ambiguity as to what the expected interpretation of lutidinyl would be, and there's not currently a class in the grammar for groups that allow inline suffixes and MUST have a locant. Hence I'll add these substituents by special case.
