### ISSUE TITLE
Error when parsing "undecahectane".

### ISSUE THREAD

**Issue by iclkevin** [dan2097/opsin#213]
I receive the following error when I use OPSIN 2.7.0 to parse "undecahectane" as a straight chain of 111 carbons: "undechect should not have been lexed as two tokens!"

I assume this is a bug. Please let me know if I can help.

**Comment by dan2097** [comment]
Thanks, I think I misinterpeted `NT-1.4 - As an exception to [Rule NT-1.3](https://iupac.qmul.ac.uk/misc/numb.html#13), the number 11 is represented by undeca- instead of hendeca-.` as applying when the chain was exactly of length 11 rather than when the number would end in 11.
