### ISSUE TITLE
Albert Hofmann's problem child

### ISSUE THREAD

**Issue by IsomerDesign** [dan2097/opsin#218]
Well, not exactly. The first example is pure (OPSIN-style) fun. The third example might need further investigation.

Below, the d- is interpreted as Deuterium, and dihydro is flagged as ambiguous:

**1-dimethylaminomethyl-d-dihydrolysergic acid methyl ester** 

This rearrangement works better, still flagged as ambiguous

**1-dimethylaminomethyl-dihydro-d-lysergic acid methyl ester** 

Yet this fails: "hydrogen addition at locant: 10 was requested, but this atom is not unsaturated"

**1-dimethylaminomethyl-9,10-dihydro-d-lysergic acid methyl ester**

**Comment by dan2097** [comment]
OPSIN treats double bonds that arise from systems that have the maximum number of non-cumulative double bonds and explicit double bonds differently, with hydro only being able to remove unsaturation indicated by the former. Given that empirically 9,10-dihydro is very commonly used, this double bond should be treated the same as the other double bonds.
Making terms like dihydrolysergic acid unambiguous requires them to be explicitly added, and I'm not not immediately convinced that `1-dimethylaminomethyl-dihydro-d-lysergic acid methyl ester` without the locants will be common.

The other two names you provided are now supported and treated as unambiguous.

**Comment by dan2097** [comment]
Actually I think I've misimplemented this, am I correct in saying that https://pubchem.ncbi.nlm.nih.gov/compound/9_10-Dihydrolysergic-acid is the intended stereochemistry i.e. the configuration at position 10 is implicitly defined

**Comment by IsomerDesign** [comment]
I don't know if the _configuration_ at 10 is implicitly defined or not. The first two examples were drawn from the literature a half century ago. They are ambiguous, and all the better for OPSIN to flag it. 

My only real issue was the rejection of explicit locants for dihydro. In other words, the more precise 9,10-dihydrolysergic acid was rejected. I'd not given any thought to the configuration at 10.

**Comment by dan2097** [comment]
Well as the reported issue is resolved, I'll close this. opsin.ch.cam.ac.uk now reflects this change
