### ISSUE TITLE
OPSIN - acknowledgement

### ISSUE THREAD

**Issue by alanliska** [dan2097/opsin#220]
Dear Professor Lowe,

me and my friend Veronika Ruzickova focus at porting professional open-source chemistry codes to Android. Recently, we have published 3 new free apps:
PHREEQC plus
https://play.google.com/store/apps/details?id=cz.p
https://github.com/alanliska/PHREEQC-plus
DFTB+
https://play.google.com/store/apps/details?id=cz.jh.dftb
https://github.com/alanliska/DFTB
XTB
https://play.google.com/store/apps/details?id=cz.jh.xtb
https://github.com/alanliska/XTB
where we utilized your BRILLIANT library 'OPSIN' for translating the IUPAC input names to SMILES (and by OpenBABEL furthermore to XYZ coordinates) in the apps. Because we plan to upgrade also some other similar apps, it is highly probable that we integrate your 'OPSIN' to them as well.
Inside of each app as well as in the individual package descriptions, we cited your software as follows:

 * OPSIN
 Authors/developers: Rich Apodaca, Albina Asadulina, Peter Corbett, Daniel Lowe (Current maintainer), John Mayfield, Peter Murray-Rust, Noel O'Boyle, Mark Williamson
 Ref.: Lowe, Daniel M., Peter T. Corbett, Peter Murray-Rust, and Robert C. Glen. "Chemical name to structure: OPSIN, an open source solution." (2011): 739-753.
 Source code: https://github.com/dan2097/opsin
 License: MIT License

Please let me know if you would like to enhance the reference to you, or specify the citation in a more detailed way.
Thank you.

Sincerely,

Alan

-- 
RNDr. Alan Liška, Ph.D.
Ústav fyzikální chemie J. Heyrovského AV ČR, v.v.i. / J. Heyrovský Institute of Physical Chemistry of the CAS, v.v.i.
Dolejškova 3/2155, 18223 Praha 8
Česká republika / Czech Republic

**Comment by dan2097** [comment]
Thanks, this looks good to me

**Comment by alanliska** [comment]
Thank you also!
