### ISSUE TITLE
Carbohydrate locant improvements: 2-phosphoglyceric acid

### ISSUE THREAD

**Issue by rogersayle** [dan2097/opsin#223]
Hopefully another easy fix.  Glyceric acid appears to be missing numeric locants.  Admittedly not definitive but the wikipedia article for  glyceric acid mentions 2-phosphoglyceric acid and 3-phophoglyceric acid, which are both interpreted by ChemDraw.  Many thanks in advance.

**Comment by dan2097** [comment]
Sorry I think I overlooked this issue. I agree this is an easy fix, with the only slight complication being to ensure phospho uses its biochemical definition.
