### ISSUE TITLE
DPPA synonyms

### ISSUE THREAD

**Issue by IngvarLa** [dan2097/opsin#226]
According to ECHA and PubChem both
diphenylphosphoryl azide
diphenoxyphosphoryl azide
corresponds to C1=CC=C(C=C1)OP(=O)(N=[N+]=[N-])OC2=CC=CC=C2
Opsin and (ChemDraw) uses 
C1=CC=C(C=C1)P(=O)(N=[N+]=[N-])C2=CC=CC=C2
for diphenylphosphoryl azide

https://echa.europa.eu/substance-information/-/substanceinfo/100.043.298
https://pubchem.ncbi.nlm.nih.gov/compound/123414#section=Depositor-Supplied-Synonyms

Guess you are technically correct, but this looks like a loosing battle.

**Comment by dan2097** [comment]
I can't think of a more elegant solution that simply special casing this name, as it describes a different structure, and diphenylphosphoryl in other names doesn't imply an oxygen
