### ISSUE TITLE
Website gives different results than Java

### ISSUE THREAD

**Issue by UWesthaus** [dan2097/opsin#229]
For the substance **_1-tetradecyl-3-methyl-1H-imidazolium chloride_**

- java -jar opsin-cli-2.7.0-jar-with-dependencies.jar -ostdinchikey return: BPGYFPOMDKAMBJ-UHFFFAOYSA-N
- website returns: SDXDXENAFAXVMX-UHFFFAOYSA-M

Why? Website seems correct. Could the *.jar builds be updated to match the website?

**Comment by dan2097** [comment]
It has been quite a while since the last release, so releasing a new version probably makes sense. I'll try and get around to doing this on the weekend. This specific case was fixed in response to https://github.com/dan2097/opsin/issues/150

**Comment by UWesthaus** [comment]
Wonderfully, thanks.
