### ISSUE TITLE
lithium triethylborodeuteride not recognized

### ISSUE THREAD

**Issue by IngvarLa** [dan2097/opsin#230]
Think this is the normal way to name 
```
[Li+].CC[B-](CC)(CC)[2H]
``` 

Opsin is happy with lithium triethylborohydride.  
Compare with Lithium aluminiumtetradeuteride and Lithium aluminium tetradeuteride which are both recognised.

**Comment by dan2097** [comment]
This was surprisingly inelegant to support as OPSIN doesn't allow implicit deuterium atoms.
e.g. `lithium triethylborohydride` has one deuterium, but `lithium borohydride` has four!

I also added support for the less common tritium analogue (borotritide)
