### ISSUE TITLE
double bond is not shown for bicyclo[3.2.1]oct-6-ene-3-carbonitrile

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#232]
Hi,

I was trying to get the structure of "bicyclo[3.2.1]oct-6-ene-3-carbonitrile". However, OPSIN doesn't seem to show the double bond that is there between the 6-7 position. I don't understand why? Here is the snap shot generated.

![bicyclo321oct-6-ene-3-carbonitrile](https://github.com/dan2097/opsin/assets/70721856/b4595eb6-d5ec-433c-b8fc-a4d17478d827)

**Comment by dan2097** [comment]
This appears to be a bug in how Indigo is depicting this molecule. The double bond line is so small that it's barely visible, I've circled it here 
![image](https://github.com/dan2097/opsin/assets/731646/3c75f19c-c2ab-4eb5-9bf7-7b99588669d8)
I've raised a bug report (https://github.com/epam/Indigo/issues/1400)

The SMILES is correct, e.g. https://www.simolecule.com/cdkdepict/depict.html will depict this as 
![png](https://github.com/dan2097/opsin/assets/731646/3285b6b7-4fe3-4d8f-b841-4cced999f1d1)

**Comment by vthimmakondu** [comment]
Thank you.
