### ISSUE TITLE
API base URL should redirect to instructions

### ISSUE THREAD

**Issue by stuchalk** [dan2097/opsin#238]
I think the base URL of the API endpoint should redirect to the instructions about the API rather than an error page.
So, https://opsin.ch.cam.ac.uk/opsin/ should redirect to https://opsin.ch.cam.ac.uk/instructions.html .

This is akin to the Crossref API that redirects http://api.crossref.org to http://api.crossref.org/swagger-ui/index.html.

If you don't want to do this you could formally define the API using swagger and point to that, again as the Crossref API does.

**Comment by dan2097** [comment]
This change is now live; I agree that a Swagger (OpenAPI) definition would probably be preferable, but I don't have immediate plans to add this
