### ISSUE TITLE
Inquiry about OPSIN's Validation of IUPAC Names

### ISSUE THREAD

**Issue by Kohulan** [dan2097/opsin#249]
Hey @dan2097,

I was wondering if OPSIN is equipped to verify whether a provided IUPAC name is valid or not. By "valid," I mean ensuring that all IUPAC priority rules and other relevant guidelines were correctly followed before constructing the structure from the given IUPAC name.

Kind regards,
Kohulan

**Comment by dan2097** [comment]
Unfortunately not. The priority rules get very complicated, and as my goal was primarily to allow intepretation of real-world names which do not always comply with the priority rules these checks have not been implemented. I think to implement them comprehensively would essentially require one to write a structure to name algorithm and then see whether the resultant name agrees with the original name!

Are you thinking of ways to test whether a name output from STOUT is compliant with these rules?

**Comment by Kohulan** [comment]
Hi @dan2097 ,

Thanks a lot for the clarification. I understand the difficulty. That is exactly what I thought as well. 

> Are you thinking of ways to test whether a name output from STOUT is compliant with these rules?

Yes, I considered retranslating the names generated by STOUT using OPSIN to determine whether it would yield the original structure.  This in theory works but we don't know how confidently we could depend on these names.

Kind regards,
Kohulan

**Comment by dan2097** [comment]
> Yes, I considered retranslating the names generated by STOUT using OPSIN to determine whether it would yield the original structure. This in theory works but we don't know how confidently we could depend on these names.

I think there is value in doing this, but not all outcomes are as actionable:

- OPSIN gives the intended structure: Name highly likely conveys the correct structure but does not neccesarily comply with IUPAC priority rules.
- OPSIN gives the wrong structure. Assuming the name was intended to be an IUPAC name, the name is highly likely to be wrong or ambiguous
- OPSIN gives no structure. This depends a bit on what STOUT was trained on. OPSIN does not support all IUPAC nomenclature (especially Inorganic nomenclature), but for generated IUPAC names e.g. those on PubChem, OPSIN likely does support practically all of this nomenclature. In short though this indicates the name is likely wrong, but definitely doesn't gurantee it.

**Comment by Kohulan** [comment]
Thanks a lot, @dan2097 , This information is valuable to convey explicitly to users who rely on STOUT for IUPAC name generation. Presently, STOUT is trained on PubChem IUPAC names generated using OpenEye LexiChem Software. 

I will make sure to include your points when we publish the next version of STOUT.
