### ISSUE TITLE
Unable to figure out the IUPAC name using OPSIN

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#251]
Hi,
I am trying to figure out the IUPAC name for one of the isomers of C2Li3. Please find the structure in the attachment. I thought that the name should be 1-lithio-2lambda2-lithio-4-lambda2-lithiobicyclo[1.1.0]butane-3-yl. However, OPSIN gives a structure that is of totally different elemental composition (C4Li3H2). How to bring the Li atom inside the butane ring? I am wondering what I am doing wrong here. Any help is appreciated. Thanks in advance.
![Screenshot 2024-04-02 at 12-32-36 OPSIN Open Parser for Systematic IUPAC Nomenclature](https://github.com/dan2097/opsin/assets/70721856/b9b6168b-bdda-4725-a59e-73059373be95)
![IMG_0831](https://github.com/dan2097/opsin/assets/70721856/8eae5f32-5a8e-4ea8-89ab-dd916f5e4b33)

**Comment by dan2097** [comment]
I'm not sure whether IUPAC would prefer an inorganic name for this compound, but I can help with an organic name:

1-lithio-2λ<sup>2</sup>,4λ<sup>2</sup>-dilithabicyclo[1.1.0]butane-3-yl

litha is the replacement term for lithium: https://iupac.qmul.ac.uk/BlueBook/Papp1.html

**Comment by vthimmakondu** [comment]
Thank you, Dan. Is it like if the valence matches (1 for lithium) we have to use "lithio" for lithium and otherwise "litha"?

**Comment by dan2097** [comment]
> Thank you, Dan. Is it like if the valence matches (1 for lithium) we have to use "lithio" for lithium and otherwise "litha"?

No, the distinction is whether a carbon is being replaced (litha) or a hydrogen is being substituted (lithio). Litha is a replacement term, while lithio is a substituent group.
Both terms assume lithium is monovalent unless specified otherwise.

**Comment by vthimmakondu** [comment]
Thank you.
