### ISSUE TITLE
Unable to get the structure of trispiro[2.0.2.0.2.0]nonane

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#253]
Hi Dan,

I am unable to get the structure of this molecule in OPSIN. Tried few other spiro compounds such as trispiro[2.0.0.2.1.1]nonane, which generates the structure but for the titled one it says "Bonds must be made between different atoms". This structure, trispiro[2.0.2.0.2.0] is available in PubChem (https://pubchem.ncbi.nlm.nih.gov/compound/141640) and I don't think the name I am entering here is wrong. In fact I even tried with superscripts of the spiro centers like trispiro[2.0.24.0.27.03]nonane. However, I got a different error message this time, "Disagreement between number of atoms in spiro descriptor: 59 and number of atoms in chain: 9". Any help is appreciated. Thanks in advance,

Venky

**Comment by dan2097** [comment]
`trispiro[2.0.2^4.0.2^7.0^3]nonane` gives the expected structure. I'll investigate whether this should work without the superscripts.
