### ISSUE TITLE
spiro[2.4]heptane-5,7-dione vs spiro[2.4]heptane-4,6-dione

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#256]
Hello,

Pubchem indicates a compound named spiro[2.4]heptane-5,7-dione. However, If I understand the IUPAC nomenclature correctly, the correct name for this should be spiro[2.4]heptane-4,6-dione as that puts the keto groups in low numbers. Though OPSIN generates the structure for both I am wondering which name is correct. 

Any help is appreciated.

Thanks

**Comment by dan2097** [comment]
OPSIN doesn't make a distinction between preferred IUPAC names and names that are formed using systematic nomenclature, so it's expected that OPSIN would interpret both names. For the same parent I'm nearly certain that preferred IUPAC names use the lower locants, so I can't think of a reason why the preferred name wouldn't be `spiro[2.4]heptane-4,6-dione`
I would assume that it's a bug in the software that generated the name, which according to PubChem is `Computed by LexiChem 2.6.6 (PubChem release 2019.06.18)`

In support of this, Marvin JS does assign the name `spiro[2.4]heptane-4,6-dione` if you save this structure as a name.

**Comment by vthimmakondu** [comment]
Thank you. In the long run, is it possible for OPSIN to recognize or make a distinction between names that are preferred versus systematic? What I mean is, is it possible to get a note right below the structure like this name is a preferred IUPAC name or this name is a systematic name. Or is it too complicated to code something of that sort in Java? Or it should be the responsibility of the individual chemist/user who should know these things by studying the IUPAC rules clearly.

**Comment by vthimmakondu** [comment]
By the way, I don't think we can call spiro[2.4]heptane-5,7-dione as systematic and the other name, spiro[2.4]heptane-4,6-dione, as preferred. I just went through the blue book again, which says that "Numbering starts in the
smaller ring, if one is smaller, at a ring atom next to the spiro atom and proceeds first around that ring, then through the
spiro atom and around the second ring". It doesn't specifically say whether one should go clockwise or counter-clockwise when we do the numbering around the first or second ring. Therefore, depending upon how one starts and how the numbering was continued we can certainly get two names. However, we know for sure that we should give low numbers for the functional groups even if we are adopting to a systematic nomenclature. Therefore, I would rather say that spiro[2.4]heptane-5,7-dione is flat out incorrect for this structure and I agree that this could possibly be a bug in the LexiChem 2.6.6.
