### ISSUE TITLE
Unable to get the structure of Bicyclo[4.1.0]heptane, 7-bicyclo[4.1.0]hept-7-ylidene

### ISSUE THREAD

**Issue by vthimmakondu** [dan2097/opsin#257]
I am unable to get the structure of this compound in OPSIN
https://pubchem.ncbi.nlm.nih.gov/compound/562714

![image](https://github.com/dan2097/opsin/assets/70721856/d6286787-fc4e-4dcb-af68-b42915fe5335)

**Comment by dan2097** [comment]
The trailing hyphen is significant as OPSIN uses this to tell if the name is a CAS index name
[Bicyclo[4.1.0]heptane, 7-bicyclo[4.1.0]hept-7-ylidene-](https://opsin.ch.cam.ac.uk#Bicyclo[4.1.0]heptane,%207-bicyclo[4.1.0]hept-7-ylidene-)
