### ISSUE TITLE
OPSIN Not working?

### ISSUE THREAD

**Issue by Cas1818** [dan2097/opsin#264]
Hello,

I'm trying to use the OPSIN website but when I enter a compound name and click submit nothing seems to happen. Been like this for 2 days now.

**Comment by mwilliams07** [comment]
I was having the same issue and so contacted the Chemistry Department earlier this morning. 

They replied "Unfortunately, we have retired this server." 

I sincerely hope not.

**Comment by dpasin** [comment]
Having the same issue. I regularly use this service so I'm hoping that the server gets brought back online

**Comment by IngvarLa** [comment]
Opsin is back. Hurrah.

**Comment by dpasin** [comment]
Thanks!

**Comment by mwilliams07** [comment]
Fantastic. Thank you very much.
