### ISSUE TITLE
undefined locant + underspecified phosphorus/sulfur atom = match 

### ISSUE THREAD

**Issue by IngvarLa** [dan2097/opsin#265]
Hi Daniel, 
Think this sums up several of the issues I have seen.
When there is a halogen atom/amino group without a locant and there is a tetravalent phosphorous/pentavalent sulfur atom, the halogen should in most cases go to the P/S. 

If I search for: `[Pv5+0:1](Cl)(Cl).[NX3v3+0:2]>>[P:1]=[N:2]` in Pistachio, I get 200+ hits, non of them intended, some examples:

(2S)-butyl 2-(chloro(phenoxy)phosphorylamino)propanoate:
`ClC1=C(OP(=O)=N[C@H](C(=O)OCCCC)C)C=CC=C1`
This one givers a warning: APPEARS_AMBIGUOUS: Connection of chloro to phenoxy
Move the amino and the chlorine ends up on the P as intended:
(2S)-butyl 2-(chloro(phenoxy)phosphoryl)aminopropanoate:
`ClP(=O)(OC1=CC=CC=C1)N[C@H](C(=O)OCCCC)C`

 (2S)-cyclohexyl 2-(chloro(naphthalen-1-yloxy)-phosphorylamino)-3-methylbutanoate
I get:
`ClC1=C(C2=CC=CC=C2C=C1)OP(=O)=N[C@H](C(=O)OC1CCCCC1)C(C)C`
Moving the chloro to:
 (2S)-cyclohexyl 2-((naphthalen-1-yloxy)-chlorophosphorylamino)-3-methylbutanoate
I get:
`C1(=CC=CC2=CC=CC=C12)OP(=O)(Cl)N[C@H](C(=O)OC1CCCCC1)C(C)C`
which is what was intended.

Here the benzylamino and amino groups do not have locants:
(2S)-Neopentyl 2-((((2R,3R,4R,5R)-5-(2-amino-6-methoxy-9H-purin-9-yl)-3,4-dihydroxy-4-methyltetrahydrofuran-2-yl)methoxy)(benzylamino)phosphorylamino)propanoate
`NC1=NC(=C2N=CN(C2=N1)[C@H]1[C@]([C@@H]([C@H](O1)CON(P(=O)=N[C@H](C(=O)OCC(C)(C)C)C)CC1=CC=CC=C1)O)(C)O)OC`
move one of the aminos to:
(2S)-Neopentyl 2-((((2R,3R,4R,5R)-5-(2-amino-6-methoxy-9H-purin-9-yl)-3,4-dihydroxy-4-methyltetrahydrofuran-2-yl)methoxy)(benzylamino)phosphoryl)aminopropanoate	
I get the intended:
`NC1=NC(=C2N=CN(C2=N1)[C@H]1[C@]([C@@H]([C@H](O1)COP(=O)(NCC1=CC=CC=C1)N[C@H](C(=O)OCC(C)(C)C)C)O)(C)O)OC`

In all three cases ChemDraw treats the names as equivalent

**Comment by dan2097** [comment]
I think this issue only effected phosphoryl (and presumably the arsenic/antimony equivalents). The implicit bracketing logic has been adjusted so that such cases expect there to be two substituents. The equivalent sulfur substituents only require one substituent.
